services:
  # Django app service
  web:
    build: .
    container_name: django_app
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true

  # PostgreSQL database service
  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data # Mounting to a host directory
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
