# Generated by Django 4.1 on 2022-08-29 19:40

from typing import Any, List

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("amount", models.FloatField(default=0)),
                ("label", models.CharField(default="", max_length=255)),
                ("date", models.DateField()),
            ],
        ),
    ]
