# Generated by Django 5.1 on 2024-09-29 09:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "membership_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("can_create_expense", models.BooleanField(default=False)),
                ("can_edit_expense", models.BooleanField(default=False)),
                ("can_delete_expense", models.BooleanField(default=False)),
                ("can_edit_trip", models.BooleanField(default=False)),
                ("can_share_trip", models.BooleanField(default=False)),
                ("can_delete_trip", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(default="", max_length=1023)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "members",
                    models.ManyToManyField(
                        through="accounting.Membership", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="trip",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.trip",
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("label", models.CharField(default="", max_length=255)),
                ("expense_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transport", "Transport"),
                            ("grocery", "Grocery"),
                            ("activity", "Activity"),
                            ("restaurant", "Restaurant"),
                            ("administrative", "Administrative"),
                        ],
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("expiry", models.DateTimeField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.trip",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="end_date_greater_than_start_date",
            ),
        ),
    ]
