# Generated by Django 4.1 on 2023-03-30 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0002_trip_alter_expense_id_expense_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="trip",
            name="owner",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
