# Generated by Django 4.1 on 2022-11-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_budget_alter_expense_id_expense_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
