# Generated by Django 5.1.4 on 2025-03-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_expense_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transport", "Transport"),
                    ("grocery", "Grocery"),
                    ("activity", "Activity"),
                    ("restaurant", "Restaurant"),
                    ("administrative", "Administrative"),
                    ("accommodation", "Accommodation"),
                ],
                max_length=14,
                null=True,
            ),
        ),
    ]
