# Generated by Django 4.1 on 2022-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_budget_alter_expense_id_expense_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(
                default="Budget-10/19/2022-15:04:22",
                max_length=255,
                unique=True,
            ),
        ),
    ]
