# Generated by Django 4.1 on 2024-02-15 17:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_trip_members_trip_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="trip",
            name="description",
            field=models.TextField(default="", max_length="1023"),
        ),
    ]
