# Generated by Django 4.1 on 2022-10-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_budget_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(
                default="Budget-10/23/2022-11:47:22", max_length=255, unique=True
            ),
        ),
    ]
