# Generated by Django 5.1.4 on 2025-06-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_trip_preferred_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUD", "Australian Dollar"),
                    ("BGN", "Bulgarian Lev"),
                    ("BRL", "Brazilian Real"),
                    ("CAD", "Canadian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("CNY", "Chinese Yuan"),
                    ("CZK", "Czech Koruna"),
                    ("DKK", "Danish Krone"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound Sterling"),
                    ("HKD", "Hong Kong Dollar"),
                    ("HUF", "Hungarian Forint"),
                    ("IDR", "Indonesian Rupiah"),
                    ("ILS", "Israeli New Shekel"),
                    ("INR", "Indian Rupee"),
                    ("ISK", "Icelandic Króna"),
                    ("JPY", "Japanese Yen"),
                    ("KRW", "South Korean Won"),
                    ("MXN", "Mexican Peso"),
                    ("MYR", "Malaysian Ringgit"),
                    ("NOK", "Norwegian Krone"),
                    ("NZD", "New Zealand Dollar"),
                    ("PHP", "Philippine Peso"),
                    ("PLN", "Polish Złoty"),
                    ("RON", "Romanian Leu"),
                    ("SEK", "Swedish Krona"),
                    ("SGD", "Singapore Dollar"),
                    ("THB", "Thai Baht"),
                    ("TRY", "Turkish Lira"),
                    ("USD", "United States Dollar"),
                    ("ZAR", "South African Rand"),
                ],
                max_length=22,
                null=True,
            ),
        ),
    ]
