# Generated by Django 4.1 on 2024-02-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_trip_date_trip_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="date",
            new_name="start_date",
        ),
    ]
