# Generated by Django 5.1.4 on 2025-06-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    def apply_default_expense_currency(apps, schema_editor):
        Expense = apps.get_model("accounting", "Expense")

        for expense in Expense.objects.all():
            expense.currency = expense.trip.preferred_currency  # pragma: no cover
            expense.save()  # pragma: no cover

    dependencies = [
        ("accounting", "0005_expense_currency"),
    ]

    operations = [migrations.RunPython(apply_default_expense_currency)]
