# Generated by Django 4.1 on 2024-02-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_rename_date_trip_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="budget",
            new_name="trip",
        ),
    ]
