# Generated by Django 4.1 on 2024-03-21 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_rename_budget_expense_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
