# Generated by Django 5.1.4 on 2025-06-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_auto_20250614_1601"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="initial_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
