# Generated by Django 5.1.4 on 2025-06-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    def apply_default_initial_amount(apps, schema_editor):
        Expense = apps.get_model("accounting", "Expense")

        for expense in Expense.objects.all():
            expense.initial_amount = expense.amount  # pragma: no cover
            expense.save()  # pragma: no cover

    dependencies = [
        ("accounting", "0007_expense_initial_amount"),
    ]

    operations = [migrations.RunPython(apply_default_initial_amount)]
