# Generated by Django 4.1 on 2024-03-22 00:51

from django.db import migrations, models

import accounting.constants


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_trip_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    (accounting.constants.Category["TRANSPORT"], "Transport"),
                    (accounting.constants.Category["GROCERY"], "Grocery"),
                    (accounting.constants.Category["ACTIVITY"], "Activity"),
                    (accounting.constants.Category["RESTAURANT"], "Restaurant"),
                    (accounting.constants.Category["ADMINISTRATIVE"], "Administrative"),
                ],
                max_length=14,
                null=True,
            ),
        ),
    ]
