# Generated by Django 5.1.4 on 2025-06-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_auto_20250614_2221"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="initial_amount",
            new_name="converted_amount",
        ),
    ]
