# Generated by Django 4.1 on 2024-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_expense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("transport", "Transport"),
                    ("grocery", "Grocery"),
                    ("activity", "Activity"),
                    ("restaurant", "Restaurant"),
                    ("administrative", "Administrative"),
                ],
                max_length=14,
                null=True,
            ),
        ),
    ]
