# Generated by Django 4.1 on 2024-03-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_alter_expense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="description",
            field=models.TextField(default="", max_length=1023),
        ),
    ]
