# Generated by Django 4.1 on 2024-03-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_alter_trip_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="end_date_greater_than_start_date",
            ),
        ),
    ]
