# Generated by Django 4.2.1 on 2024-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_alter_trip_end_date_alter_trip_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
