# Generated by Django 4.2.1 on 2024-03-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_trip_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="date",
            new_name="expense_date",
        ),
    ]
