# Generated by Django 4.2.1 on 2024-03-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0013_rename_date_expense_expense_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
