# Generated by Django 4.2.1 on 2024-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_alter_expense_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
