# Generated by Django 4.2.11 on 2024-04-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_trip_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
