# Generated by Django 4.2.11 on 2024-04-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_trip_reference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="reference",
            new_name="token",
        ),
    ]
