# Generated by Django 4.2.11 on 2024-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0018_rename_reference_trip_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="token_expiry",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
