# Generated by Django 4.2.11 on 2024-04-21 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0019_trip_token_expiry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="token",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="token_expiry",
        ),
        migrations.CreateModel(
            name="TripToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("expiry", models.DateTimeField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.trip",
                    ),
                ),
            ],
        ),
    ]
