# Generated by Django 4.2.11 on 2024-05-14 08:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0020_remove_trip_token_remove_trip_token_expiry_triptoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("can_create_expense", models.BooleanField(default=False)),
                ("can_edit_expense", models.BooleanField(default=False)),
                ("can_delete_expense", models.BooleanField(default=False)),
                ("can_edit_trip", models.BooleanField(default=False)),
                ("can_share_trip", models.BooleanField(default=False)),
                (
                    "trip",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounting.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
