# Generated by Django 4.2.11 on 2024-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="can_delete_trip",
            field=models.BooleanField(default=False),
        ),
    ]
