# Generated by Django 5.1 on 2024-08-30 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_membership_can_delete_trip"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="membership_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
